#
# MIT License
#
# Copyright (c) 2025 Elektroline
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: "Rust nightly release"
description: "Generate nightly releases for Rust projects"
inputs:
  path_glob:
    description: "Path glob to be used for release assets"
    required: true

runs:
  using: "composite"
  steps:
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "nightly"
        force_push_tag: true

    - name: Delete previous nightly release
      shell: bash
      run:
        # Deleting the release refreshes the release date.
        gh release delete nightly || true

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: Nightly
        tag_name: nightly
        fail_on_unmatched_files: true
        body: |
          The latest and greatest.

          This is a nightly release. If you find any bugs, please report them to the repository's issue tracker.
        files: |
           ${{inputs.path_glob}}


branding:
  icon: "tag"
  color: "gray-dark"
